import {neural} from './neural.ts';
export type Point = {x:number;y:number;z:number;intensity?:number;label?:number};
export type Cell = {key:string;x:number;y:number;r0:number;r1:number;a0:number;a1:number;tier:number;size:number;min:number;max:number;mean:number;m2:number;roughness:number;count:number;votes:number[];label:number;confidence:number};
export type Config = {near:number;mid:number;far:number;nearSize:number;midSize:number;farSize:number};
export const DEFAULT:Config={near:10,mid:30,far:100,nearSize:.05,midSize:.15,farSize:.5};
export const CLASSES=['Drivable terrain','Non-drivable terrain','Static obstacles','Dynamic objects'];
export const COLOURS=['#38d6ad','#e4b35f','#7f9cfc','#f47d92'];
export function validateConfig(c:Config){if(!Object.values(c).every(Number.isFinite)||!(0<c.near&&c.near<c.mid&&c.mid<c.far&&c.far<=100)||!(c.nearSize>=.05&&c.midSize>=c.nearSize&&c.farSize>=c.midSize&&c.farSize<=2))throw Error('Use increasing radii up to 100 m and cell sizes from 0.05 to 2 m.');}
export function geometry(p:Point){return p.z < -.15 ? 1 : p.z < .18 ? 0 : p.z < .45 ? 1 : 2;}
export function address(p:Point,c:Config=DEFAULT){const r=Math.hypot(p.x,p.y);if(![p.x,p.y,p.z].every(Number.isFinite)||r>c.far)return null;const tier=r<c.near?0:r<c.mid?1:2;const start=[0,c.near,c.mid][tier],end=[c.near,c.mid,c.far][tier],size=[c.nearSize,c.midSize,c.farSize][tier];const bins=Math.ceil((end-start)/size);const ring=Math.min(bins-1,Math.floor((r-start)/size));const r0=start+ring*size,r1=Math.min(end,r0+size);const n=Math.max(1,Math.ceil(2*Math.PI*((r0+r1)/2)/size));const a=(Math.atan2(p.y,p.x)+Math.PI*2)%(Math.PI*2),sector=Math.min(n-1,Math.floor(a/(2*Math.PI)*n));const a0=sector/n*2*Math.PI,a1=(sector+1)/n*2*Math.PI,rm=(r0+r1)/2,am=(a0+a1)/2;return {key:`${tier}:${ring}:${sector}`,x:rm*Math.cos(am),y:rm*Math.sin(am),r0,r1,a0,a1,tier,size};}
export function project(points:Point[],c:Config=DEFAULT,source:'labels'|'geometry'|'neural'='labels'){
 validateConfig(c);const t=performance.now(),map=new Map<string,Cell>();let dropped=0;const pointLabels:number[]=[];const confusion=Array.from({length:4},()=>[0,0,0,0]);let labelled=0;const buckets=Array.from({length:3},()=>({total:0,correct:0}));
 for(const p of points){const pred=source==='neural'?neural(p):geometry(p);pointLabels.push(pred);const a=address(p,c);if(!a){dropped++;continue;}if(Number.isInteger(p.label)&&p.label!>=0&&p.label!<4){confusion[p.label!][pred]++;labelled++;buckets[a.tier].total++;buckets[a.tier].correct+=pred===p.label?1:0;}const label=source==='labels'&&Number.isInteger(p.label)&&p.label!>=0&&p.label!<4?p.label!:pred;let cell=map.get(a.key);if(!cell){cell={...a,min:p.z,max:p.z,mean:0,m2:0,roughness:0,count:0,votes:[0,0,0,0],label,confidence:0};map.set(a.key,cell);}cell.count++;const d=p.z-cell.mean;cell.mean+=d/cell.count;cell.m2+=d*(p.z-cell.mean);cell.min=Math.min(cell.min,p.z);cell.max=Math.max(cell.max,p.z);cell.votes[label]++;}
 for(const cell of map.values()){cell.label=cell.votes.indexOf(Math.max(...cell.votes));cell.confidence=Math.max(...cell.votes)/cell.count;cell.roughness=Math.sqrt(cell.m2/cell.count);}
 const uniform=new Set<string>();for(const p of points)if(address(p,c))uniform.add(`${Math.floor(p.x/c.nearSize)}:${Math.floor(p.y/c.nearSize)}`);
 const iou=confusion.map((row,i)=>{const union=row.reduce((a,b)=>a+b,0)+confusion.reduce((s,r)=>s+r[i],0)-row[i];return union?row[i]/union:null;});const present=iou.filter((x):x is number=>x!==null);
 return {pointLabels,cells:[...map.values()],accepted:points.length-dropped,dropped,latency:performance.now()-t,bytes:map.size*64,uniformBytes:uniform.size*64,confusion,iou,miou:present.length?present.reduce((a,b)=>a+b,0)/present.length:null,labelled,buckets};
}
export function simulate(frame=0,scene='urban'):Point[]{let seed=42;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};const p:Point[]=[];const add=(x:number,y:number,z:number,label:number)=>p.push({x,y,z,label,intensity:.3+rand()*.7});
 for(let i=0;i<11500;i++){const x=(rand()-.5)*145,y=(rand()-.5)*90;let z=(rand()-.5)*.04,label=0;if(Math.abs(y)>7){label=1;z=.2+(rand()-.5)*.08;}if(scene==='rugged'){z=.4*Math.sin(x*.22)*Math.cos(y*.25)+(rand()-.5)*.1;label=Math.abs(z)>.16?1:0;}if(scene==='hazards'&&Math.hypot(x-7,y-1)<2){z=-.45+rand()*.12;label=1;}add(x,y,z,label);}
 const box=(cx:number,cy:number,w:number,d:number,h:number,label:number,n:number)=>{for(let i=0;i<n;i++){let x=(rand()-.5)*w,y=(rand()-.5)*d,z=rand()*h;const face=i%3;if(face===0)x=(i%2?.5:-.5)*w;if(face===1)y=(i%2?.5:-.5)*d;if(face===2)z=h;add(cx+x,cy+y,z,label);}};
 if(scene!=='rugged'){for(let i=0;i<8;i++){box(-51+i*15,15,9,7,4+rand()*7,2,400);box(-47+i*15,-18,10,9,5+rand()*5,2,400);}for(let x=-50;x<55;x+=15)box(x,8,.2,.2,4,2,70);}else for(let i=0;i<20;i++)box((rand()-.5)*100,(rand()-.5)*60,1+rand()*2,2,1+rand()*2,2,70);
 box(-15+(frame*.45)%90,3,4.5,1.9,1.6,3,380);box(32-(frame*.25)%80,-3.5,4,1.8,1.5,3,320);box(8,6-Math.sin(frame*.035)*3,.5,.5,1.7,3,85);box(-11,5.8,.5,.5,1.7,3,85);return p;}
export function parseCSV(text:string):Point[]{const lines=text.trim().split(/\r?\n/);if(!lines.length)throw Error('The file is empty.');const first=lines[0].split(',').map(s=>s.trim().toLowerCase());const header=first.includes('x');const keys=header?first:['x','y','z','intensity','label'];if(!['x','y','z'].every(k=>keys.includes(k)))throw Error('CSV requires x, y and z columns.');const out:Point[]=[];for(const [i,line]of lines.slice(header?1:0).entries()){if(!line.trim())continue;const cols=line.split(',').map(s=>s.trim());const get=(key:string)=>{const n=keys.indexOf(key);return n>=0&&cols[n]!==''&&cols[n]!==undefined?Number(cols[n]):undefined;};const x=get('x'),y=get('y'),z=get('z'),label=get('label');if(![x,y,z].every(v=>typeof v==='number'&&Number.isFinite(v)))throw Error(`Invalid coordinates on data row ${i+1}.`);if(label!==undefined&&(!Number.isInteger(label)||label<0||label>3))throw Error(`Labels must be 0–3 (row ${i+1}).`);out.push({x:x!,y:y!,z:z!,intensity:get('intensity'),label});if(out.length>250000)throw Error('Maximum 250,000 points per browser scan.');}if(!out.length)throw Error('No points found.');return out;}
export function parseBin(buffer:ArrayBuffer):Point[]{if(!buffer.byteLength||buffer.byteLength%16)throw Error('KITTI .bin requires float32 x/y/z/intensity records (16 bytes each).');if(buffer.byteLength/16>250000)throw Error('Maximum 250,000 points per browser scan.');const v=new DataView(buffer),p:Point[]=[];for(let i=0;i<buffer.byteLength;i+=16){const x=v.getFloat32(i,true),y=v.getFloat32(i+4,true),z=v.getFloat32(i+8,true),intensity=v.getFloat32(i+12,true);if(![x,y,z,intensity].every(Number.isFinite))throw Error('Non-finite value in binary scan.');p.push({x,y,z,intensity});}return p;}
